version: "3"
services:
  website:
    build:
      context: ./vuesaxwebsite
    ports:
      - "3000:80"
    depends_on:
      - "db"
  db:
    build:
      context: ./bdd
    container_name: maria-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3001:3306"
  backend:
    build:
      context: ./storyAPI
    container_name: rest-api
    ports:
      - "8080:8080"
    depends_on:
      - "db"
